name: Build
on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  release:
    types: [ published ]

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'release' || ! github.event.release.draft }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set Version Number
        id: version
        run: |
          if [[ $GITHUB_REF_TYPE == "tag" ]]; then
            echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
            echo "filename=mec-ics-${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
          else
            echo "version=" >> $GITHUB_OUTPUT
            echo "filename=mec-ics" >> $GITHUB_OUTPUT
          fi
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer
      - name: Install dependencies
        run: composer install --no-progress
      - name: Build Plugin
        run: |
          composer run-script build -- --version "$VERSION" --zip --filename "$FILENAME"
        env:
          VERSION: ${{ steps.version.outputs.version }}
          FILENAME: ${{ steps.version.outputs.filename }}.zip
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ steps.version.outputs.filename }}
          path: |
            build/
            !build/*.zip
          if-no-files-found: error
      - name: Publish Release Assets
        if: ${{ github.event_name == 'release' }}
        run: >
          gh release upload
          --repo "$GITHUB_REPOSITORY"
          "${GITHUB_REF_NAME}"
          "build/$FILENAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILENAME: ${{ steps.version.outputs.filename }}.zip
